spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/xiaomi-test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: achanyao
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
